devops: verify clean tree on bots after build

diff --git a/.github/workflows/infra.yml b/.github/workflows/infra.yml
--- a/.github/workflows/infra.yml
+++ b/.github/workflows/infra.yml
@@ -23,6 +23,13 @@ jobs:
     - run: npm ci
     - run: npm run build
     - run: npm run lint
+    - name: Verify clean tree
+      run: |
+        if [[ -n $(git status -s) ]]; then
+          echo "ERROR: tree is dirty after npm run build:"
+          git diff
+          exit 1
+        fi
 
   build-playwright-driver:
     name: "build-playwright-driver"
